### ISSUE TITLE
cmd injectation error

### ISSUE THREAD

**Issue by khanjanny** [amcai/myscan#7]
having error

```
Traceback (most recent call last):
  File "/mnt/c/Users/Khan/Desktop/tools/myscan/myscan/lib/core/pythonpoc.py", line 43, in run
    class_poc.verify()
  File "/mnt/c/Users/Khan/Desktop/tools/myscan/myscan/pocs/perscheme/myscan_cmd_inject.py", line 40, in verify
    {"cmd": "{}*{}" % num1, "show": num1num2, "method": "w"},
TypeError: not all arguments converted during string formatting
```

**Comment by amcai** [comment]
ok ,already fix it ,thank you.
